Added convensions, resources and links
enhance-manageiq/docs pull request #10
Opened 2018-01-29 10:33 UTC by KhushbuB

Fixed #3 
Added Convensions and resources to the book.
Signed-off-by: KhushbuB <khushbu.borole@gmail.com>

2018-01-29 16:58 UTC, akshay196 commented
LGTM

2018-01-30 05:14 UTC, son-vyas commented
I think the written content still needs an attention.

2018-02-01 05:46 UTC, omkar0496 requested changes

2018-02-01 05:46 UTC, omkar0496 commented on README.md
I think 'Openstack' word should be 'OpenStack'. Same applies to all the text.

2018-02-01 05:59 UTC, son-vyas commented
I feel like following content is missing:-
1. Need for integration for OpenStack provider in ManageIQ
2. Need for Ansible integration

2018-02-01 07:55 UTC, son-vyas commented on README.md
>  - [**_Chapter 1_**](chapter1/README.md): This contains the introduction of the main constrain of the project i.e. ManageIQ. ManageIQ installation, its appliance console and basic configuration is als
It should be **'constraint'** I guess?

2018-02-02 08:04 UTC, son-vyas commented
LGTM

2018-02-02 08:26 UTC, akshay196 commented
@KhushbuB  Thank you.

2018-02-02 08:27 UTC, merged